UNAUTHORIZED_STATUS_CODE = 401
UNAUTHORIZED_ERROR_MESSAGE = "Incorrect API token"
UNAUTHORIZED_RESPONSE = {"error": UNAUTHORIZED_ERROR_MESSAGE}

FORBIDDEN_STATUS_CODE = 403
FORBIDDEN_ERROR_MESSAGE = "Access forbidden"
FORBIDDEN_RESPONSE = {"errors": FORBIDDEN_ERROR_MESSAGE}

NOT_FOUND_STATUS_CODE = 404
NOT_FOUND_ERROR_MESSAGE = "Not Found"
NOT_FOUND_RESPONSE = {"error": NOT_FOUND_ERROR_MESSAGE}

RATE_LIMIT_ERROR_STATUS_CODE = 429
RATE_LIMIT_ERROR_MESSAGE = "Rate limit exceeded"
RATE_LIMIT_ERROR_RESPONSE = {"errors": RATE_LIMIT_ERROR_MESSAGE}

INTERNAL_SERVER_ERROR_STATUS_CODE = 500
INTERNAL_SERVER_ERROR_MESSAGE = "Unexpected error"
INTERNAL_SERVER_ERROR_RESPONSE = {"errors": "Unexpected error"}

VALIDATION_ERRORS_STATUS_CODE = 422
